#!/usr/bin/with-contenv bash
set -e

export PUID=${PUID:-1000}
export PGID=${PGID:-1000}

find /var/www/html ! -group ${PGID} -exec chown ${PUID}.${PGID} {} \;
find /var/www/html ! -user ${PUID} -exec chown ${PUID} {} \;

find /var/www/html/ -type d ! -perm 0500 -exec chmod 0500 {} \;
find /var/www/html/ -type f ! -perm 0400 -exec chmod 0400 {} \;
